In [20]:
import pandas as pd

In [21]:
df = pd.read_csv('dataset/dataset.csv')

In [22]:
df

news      type
0     China had role in Yukos split-up\n \n China le...  business
1     Oil rebounds from weather effect\n \n Oil pric...  business
2     Indonesia 'declines debt freeze'\n \n Indonesi...  business
3     $1m payoff for former Shell boss\n \n Shell is...  business
4     US bank in $515m SEC settlement\n \n Five Bank...  business
5     Verizon 'seals takeover of MCI'\n \n Verizon h...  business
6     Parmalat boasts doubled profits\n \n Parmalat,...  business
7     US seeks new $280bn smoker ruling\n \n The US ...  business
8     Steel firm 'to cut' 45,000 jobs\n \n Mittal St...  business
9     Cars pull down US retail figures\n \n US retai...  business
10    Singapore growth at 8.1% in 2004\n \n Singapor...  business
11    UK bank seals South Korean deal\n \n UK-based ...  business
12    ECB holds rates amid growth fears\n \n The Eur...  business
13    Rank 'set to sell off film unit'\n \n Leisure ...  business
14    US adds more jobs than expected\n \n The US ec...  business
15    House prices show slight increase\n \n Prices ...  business
16    Pension hitch for long-living men\n \n Male li...  business
17    Asian quake hits European shares\n \n Shares i...  business
18    Honda wins China copyright ruling\n \n Japan's...  business
19    Bank set to leave rates on hold\n \n UK intere...  business
20    Macy's owner buys rival for $11bn\n \n US reta...  business
21    China suspends 26 power projects\n \n China ha...  business
22    High fuel prices hit BA's profits\n \n British...  business
23    Ebbers denies WorldCom fraud\n \n Former World...  business
24    Oil prices fall back from highs\n \n Oil price...  business
25    Bank voted 8-1 for no rate change\n \n The dec...  business
26    US trade deficit widens sharply\n \n The gap b...  business
27    Japan bank shares up on link talk\n \n Shares ...  business
28    Hyundai to build new India plant\n \n South Ko...  business
29    US in EU tariff chaos trade row\n \n The US ha...  business
...                                                 ...       ...
2195  Gadget growth fuels eco concerns\n \n Technolo...      tech
2196  Microsoft releases bumper patches\n \n Microso...      tech
2197  Row brewing over peer-to-peer ads\n \n Music d...      tech
2198  File-swappers ready new network\n \n Legal att...      tech
2199  Yahoo moves into desktop search\n \n Internet ...      tech
2200  Bush website blocked outside US\n \n Surfers o...      tech
2201  Mobile multimedia slow to catch on\n \n There ...      tech
2202  Anti-spam laws bite spammer hard\n \n The net'...      tech
2203  Hollywood campaign hits websites\n \n Movie st...      tech
2204  More movies head to Sony's PSP\n \n Movies Ope...      tech
2205  TV's future down the phone line\n \n Internet ...      tech
2206  Open source leaders slam patents\n \n The war ...      tech
2207  Mobile music challenges 'iPod age'\n \n Nokia ...      tech
2208  Dozens held over ID fraud site\n \n Twenty-eig...      tech
2209  Lasers help bridge network gaps\n \n An Indian...      tech
2210  Mobiles rack up 20 years of use\n \n Mobile ph...      tech
2211  US peer-to-peer pirates convicted\n \n The fir...      tech
2212  Broadband challenges TV viewing\n \n The numbe...      tech
2213  Gadgets galore on show at fair\n \n The 2005 C...      tech
2214  Text message record smashed again\n \n UK mobi...      tech
2215  Apple makes blogs reveal sources\n \n Apple ha...      tech
2216  Big war games battle it out\n \n The arrival o...      tech
2217  Friends fear' with lost mobiles\n \n People ar...      tech
2218  Podcasts mark rise of DIY radio\n \n An Apple ...      tech
2219  Microsoft releases patches\n \n Microsoft has ...      tech
2220  Microsoft launches its own search\n \n Microso...      tech
2221  Warnings about junk mail deluge\n \n The amoun...      tech
2222  Microsoft gets the blogging bug\n \n Software ...      tech
2223  Gamers snap up new Sony PSP\n \n Gamers have b...      tech
2224  Apple laptop is 'gr

In [23]:
df.sample(5, random_state=0)

news      type
384   Jobs go at Oracle after takeover\n \n Oracle h...  business
1983  Virgin Radio offers 3G broadcast\n \n UK broad...      tech
985   Kennedy looks to election gains\n \n They may ...  politics
1386  Pountney handed ban and fine\n \n Northampton ...     sport
1294  UK set to cut back on embassies\n \n Nine over...  politics

In [24]:
df.groupby('type')

In [35]:
df['type'].value_counts()

sport            511
business         510
politics         417
tech             401
entertainment    386
Name: type, dtype: int64

In [58]:
import plotly as py

from plotly.offline import init_notebook_mode, iplot
import plotly.graph_objs as go

import os
init_notebook_mode(connected=True)


trace1 = go.Histogram(
    x=df['type'], opacity=0.75, name="2011", marker=dict(color='rgb(0, 180, 0)'))
data = [trace1]
layout = dict(
    title='Variation of Types of News',
    xaxis=dict(title='Type of news'),
    yaxis=dict(title='Count'),
)
fig = go.Figure(data=data, layout=layout)
iplot(fig)

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(sublinear_tf=True, min_df=5, norm='l2',
                        encoding='latin-1', ngram_range=(1, 2), stop_words='english')

X = tfidf.fit_transform(df.news)
y = df.type
X.shape

(2225, 14415)

In [27]:
X

<2225x14415 sparse matrix of type '<class 'numpy.float64'>'
	with 336760 stored elements in Compressed Sparse Row format>

In [28]:
import re
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from textblob import Word
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, cohen_kappa_score, confusion_matrix

In [29]:
def clean_str(string):
    """
    Tokenization/string cleaning for datasets.
    Original taken from https://github.com/yoonkim/CNN_sentence/blob/master/process_data.py
    """
    string = re.sub(r"\'s", "", string)
    string = re.sub(r"\'ve", "", string)
    string = re.sub(r"n\'t", "", string)
    string = re.sub(r"\'re", "", string)
    string = re.sub(r"\'d", "", string)
    string = re.sub(r"\'ll", "", string)
    string = re.sub(r",", "", string)
    string = re.sub(r"!", " ! ", string)
    string = re.sub(r"\(", "", string)
    string = re.sub(r"\)", "", string)
    string = re.sub(r"\?", "", string)
    string = re.sub(r"'", "", string)
    string = re.sub(r"[^A-Za-z0-9(),!?\'\`]", " ", string)
    string = re.sub(r"[0-9]\w+|[0-9]", "", string)
    string = re.sub(r"\s{2,}", " ", string)
    return string.strip().lower()

In [30]:
y = df['type'].tolist()
Y = np.array(y)

print("no of features extracted:", X.shape[1])

X_train, X_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.20, random_state=42)

print("train size:", X_train.shape)
print("test size:", X_test.shape)

model = RandomForestClassifier(n_estimators=300, max_depth=150, n_jobs=1)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
c_mat = confusion_matrix(y_test, y_pred)
kappa = cohen_kappa_score(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)
print("Confusion Matrix:\n", c_mat)
print("\nKappa: ", kappa)
print("\nAccuracy: ", acc)

no of features extracted: 14415
train size: (1780, 14415)
test size: (445, 14415)
Confusion Matrix:
 [[111   1   2   0   1]
 [  2  68   1   1   0]
 [  1   0  74   0   1]
 [  0   0   0 102   0]
 [  3   1   0   3  73]]

Kappa:  0.951774125686892

Accuracy:  0.9617977528089887


In [59]:
import pickle
s = pickle.dumps(model)